from tkinter import *
window = Tk()
window.geometry("400x400")
frame = Frame(window)
frame.place(x=125,y=100)
button1=Button(frame, text = "Choco", fg = "brown")
button1.pack(side=LEFT)
button2 = Button(frame, text = "Dark Choco", fg = "black")
button2.pack(side=LEFT)
button3 = Button(frame, text = "White Choco", fg = "yellow")
button3.pack(side=LEFT)
frame2 = Frame(window)
frame2.place(x=325, y=275)
button4=Button(frame2, text = "Tiramisu", fg = "brown")
button4.pack()
button5 = Button(frame2, text  = "Cake", fg = "purple")
button5.pack()
button6 = Button(frame2, text = "Pastry", fg = "orange")
button6.pack()
window.mainloop()